### ISSUE TITLE
[issues] list

### ISSUE THREAD

**Issue by Alice52** [Alice52/common-api#26]
## todo list

- [x] 1. database module disable by annotation
- [x] 2. redis module disable by annotation
- [x] 3.  core module confige default value for  `mvc.async.request-timeout`
- [x] 4. update spring boot to 2.6.x
- [x] 5. search about sonar coverage
- [x] 6. add flyway to db-module for executing db-script
- [x] 7. create bom to manage version

**Comment by Alice52** [comment]
1. update spring boot to 2.6.x
